pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-central-1'
        AWS_ACCOUNT_ID = '470646073586'
        ECR_REPO = 'aws-project-app'
        IMAGE_TAG = "backend-${BUILD_NUMBER}"
        ECR_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', 
                    credentialsId: 'github-credential',
                    url: 'https://github.com/Yousefnaderr/aws-jenkins-cicd'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('small-backend-project') {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('small-backend-project') {
                    sh '''
                        . venv/bin/activate
                        pytest tests/ --maxfail=1 --disable-warnings -q
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('small-backend-project') {
                    sh '''
                        docker build -t ${ECR_REPO}:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Login & Push to ECR') {
            steps {
                withAWS(region: "${AWS_REGION}", credentials: 'aws-credentials') {
                    sh '''
                        echo "Logging in to ECR..."
                        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}
                        
                        echo "Tagging and pushing image..."
                        docker tag ${ECR_REPO}:${IMAGE_TAG} ${ECR_URI}:${IMAGE_TAG}
                        docker push ${ECR_URI}:${IMAGE_TAG}
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh '''
                echo "Connecting to EC2 and deploying container..."
                ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/aws-key.pem ubuntu@10.0.1.92 << 'EOF'
                    echo "Pulling latest image from ECR..."
                    docker login -u AWS -p $(aws ecr get-login-password --region eu-central-1) 470646073586.dkr.ecr.eu-central-1.amazonaws.com || true
                    docker pull 470646073586.dkr.ecr.eu-central-1.amazonaws.com/aws-project-app:${IMAGE_TAG}

                    echo "Stopping old container if exists..."
                    docker stop backend-app || true
                    docker rm backend-app || true

                    echo "Running new container..."
                    docker run -d -p 80:80 --name backend-app 470646073586.dkr.ecr.eu-central-1.amazonaws.com/aws-project-app:${IMAGE_TAG}
                EOF
                '''
            }
        }
    }

    post {
        success {
            echo 'Build and deployment succeeded!'
        }
        failure {
            echo 'Build or deployment failed.'
        }
        always {
            cleanWs()
        }
    }
}

