pipeline {
    agent any

    environment {
        AWS_REGION      = 'eu-central-1'
        ECR_REPO        = 'aws-project-app'
        IMAGE_TAG       = "backend-${env.BUILD_NUMBER}"
        APP_DIR         = 'small-backend-project'
        AWS_CREDENTIALS = credentials('aws-credentials')
        EC2_HOST        = '10.0.1.92'
        SSH_KEY_PATH    = '/var/lib/jenkins/aws-key.pem'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        . venv/bin/activate
                        pytest tests/ --maxfail=1 --disable-warnings -q
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        docker build -t $ECR_REPO:$IMAGE_TAG .
                    '''
                }
            }
        }

        stage('Login & Push to ECR') {
            steps {
                withAWS(credentials: 'aws-credentials', region: "${AWS_REGION}") {
                    sh '''
                        AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                        ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO"

                        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
                        docker tag $ECR_REPO:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
                        docker push $ECR_URI:$IMAGE_TAG
                    '''
                }
            }
        }

        stage('Deploy to EC2') {
            steps {
                sh '''
                    echo "Connecting to EC2 and deploying container..."
                    AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                    ECR_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO"

                    ssh -o StrictHostKeyChecking=no -i $SSH_KEY_PATH ubuntu@$EC2_HOST << 'EOF'
                        echo "Pulling latest image and restarting container..."

                        # Login and pull the latest image
                        sudo docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $ECR_URI
                        sudo docker pull $ECR_URI:$IMAGE_TAG

                        #Stop and remove any container using port 80 (if exists)
                        sudo docker ps -q --filter "publish=80" | grep -q . && \
                        sudo docker stop $(sudo docker ps -q --filter "publish=80") && \
                        sudo docker rm $(sudo docker ps -q --filter "publish=80")

                        # Run new backend container
                        sudo docker run -d -p 80:5000 --name backend-app $ECR_URI:$IMAGE_TAG

                        echo "Deployment done successfully!"
                    EOF
                '''
            }
        }
    }

    post {
        success {
            echo "Deployment completed successfully!"
        }
        failure {
            echo "Build or deployment failed — check logs above."
        }
        always {
            cleanWs()
        }
    }
}

